### PR TITLE
R6/array discriminator

### PR DESCRIPTION
**Pull request by B-Stefan**
try to use an template, found at .github/PULL_REQUEST_TEMPLATE/
[here](https://github.com/szokodiakos/typegoose/tree/master/.github/PULL_REQUEST_TEMPLATE)
please dont forget to click on raw, and copy that, not the already "compiled" one

### CODE REVIEW

**Comment by hasezoey** [comment]
as a first impression: i dont really like to use / see `// @ts-ignore` outside of testing environments
-> could you think of a way to remove them & have typescript not complaining?

**Comment by B-Stefan** [comment]
Totally agree with you! It's a heavy WIP code. 
My question is more about the feature itself and the configuration by annotations like in the example https://github.com/hasezoey/typegoose/issues/25#issue-490391823. If you decide that this is the way to implement this I will work on a more cleaner solution.

**Comment by hasezoey** [comment]
like i said in hasezoey#25, i will look into other feature-adding / enhancements after hasezoey#23

**Comment by hasezoey** [comment]
is this branch / PR still needed, or did an other pr(on the new main repo) already do this?

**Comment by B-Stefan** [comment]
The feature is still needed but this PR is out of date and just a prototype. So pr closed!

**Pull request closed without merging**
